# Dependencies
markdown: redcarpet
rouge: true

# Permalinks
permalink: /:categories/:title.html

# Setup
title: Edd Yerburgh
tagline: 'Software Engineer'

url: https://eddyerburgh.me

author:
  name: 'Edd Yerburgh'
  url: https://github.com/eddyerburgh

paginate: 5

# Custom vars
version: 2.0.0

gems:
  - jekyll-seo-tag
  - jekyll-paginate